jms_serializer:
    metadata:
        auto_detection: true
        directories:
            TaggableDoctrineExtensions:
                namespace_prefix: "DoctrineExtensions\\Taggable"
                path: "@TagBundle/Resources/config/serializer/DoctrineExtensions"
            DreamBundle:
                namespace_prefix: "DreamBundle"
                path: "%kernel.root_dir%/serializer/GeekHub/DreamBundle"
